"""fase3: variations.catatan

Revision ID: 0a4bfcf71d0c
Revises: db21bb7ae641
Create Date: 2026-08-01 22:31:22.463481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4bfcf71d0c'
down_revision: Union[str, Sequence[str], None] = 'db21bb7ae641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variations', schema=None) as batch_op:
        batch_op.drop_column('catatan')

    # ### end Alembic commands ###
