"""fase2: rap tables + spk fk

Revision ID: 6c36c95efafb
Revises: 73048d8d0a9b
Create Date: 2026-08-01 21:29:16.735555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c36c95efafb'
down_revision: Union[str, Sequence[str], None] = '73048d8d0a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=True),
    sa.Column('uraian', sa.String(length=300), nullable=True),
    sa.Column('satuan', sa.String(length=20), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('harga_satuan_jual', sa.Float(), nullable=True),
    sa.Column('total_jual', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_boq_items_project_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rap_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('versi', sa.String(length=20), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('disusun_oleh', sa.String(length=100), nullable=True),
    sa.Column('catatan_revisi', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_rap_versions_project_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prelim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rap_version_id', sa.Integer(), nullable=False),
    sa.Column('uraian', sa.String(length=300), nullable=True),
    sa.Column('biaya_per_bulan', sa.Float(), nullable=True),
    sa.Column('durasi_rencana_bulan', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_prelim_items_project_id'),
    sa.ForeignKeyConstraint(['rap_version_id'], ['rap_versions.id'], name='fk_prelim_items_rap_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rap_version_id', sa.Integer(), nullable=False),
    sa.Column('kode_rap', sa.String(length=50), nullable=True),
    sa.Column('boq_item_id', sa.Integer(), nullable=True),
    sa.Column('uraian_baku', sa.String(length=300), nullable=True),
    sa.Column('jenis_biaya', sa.String(length=20), nullable=True),
    sa.Column('satuan', sa.String(length=20), nullable=True),
    sa.Column('vol_boq', sa.Float(), nullable=True),
    sa.Column('faktor', sa.Float(), nullable=True),
    sa.Column('vol_rap', sa.Float(), nullable=True),
    sa.Column('hsat_rap', sa.Float(), nullable=True),
    sa.Column('total_rap', sa.Float(), nullable=True),
    sa.Column('sumber_harga', sa.String(length=20), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], name='fk_rap_items_boq_item_id'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_rap_items_project_id'),
    sa.ForeignKeyConstraint(['rap_version_id'], ['rap_versions.id'], name='fk_rap_items_rap_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rap_version_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=True),
    sa.Column('nilai', sa.Float(), nullable=True),
    sa.Column('pemicu', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nilai_terpakai', sa.Float(), nullable=True),
    sa.Column('tanggal_perubahan', sa.Date(), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_risk_allowances_project_id'),
    sa.ForeignKeyConstraint(['rap_version_id'], ['rap_versions.id'], name='fk_risk_allowances_rap_version_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_spks_rap_item_id', 'rap_items', ['rap_item_id'], ['id'])
        batch_op.create_foreign_key('fk_spks_prelim_item_id', 'prelim_items', ['prelim_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spks_prelim_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_spks_rap_item_id', type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('risk_allowances')
    op.drop_table('rap_items')
    op.drop_table('prelim_items')
    op.drop_table('rap_versions')
    op.drop_table('boq_items')
    # ### end Alembic commands ###
