"""fase4: accruals, cvr_periods, cvr_lines, cvr_commentaries

Revision ID: 7fdb696d949e
Revises: 0a4bfcf71d0c
Create Date: 2026-08-01 23:09:47.083792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdb696d949e'
down_revision: Union[str, Sequence[str], None] = '0a4bfcf71d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvr_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('periode', sa.String(length=10), nullable=True),
    sa.Column('cutoff_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('disusun_oleh', sa.String(length=100), nullable=True),
    sa.Column('tanggal_final', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_cvr_periods_project_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cvr_commentaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cvr_period_id', sa.Integer(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=True),
    sa.Column('penyusun', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cvr_period_id'], ['cvr_periods.id'], name='fk_cvr_commentaries_cvr_period_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cvr_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cvr_period_id', sa.Integer(), nullable=False),
    sa.Column('rap_item_id', sa.Integer(), nullable=True),
    sa.Column('value_certified', sa.Float(), nullable=True),
    sa.Column('value_internal', sa.Float(), nullable=True),
    sa.Column('cost_actual', sa.Float(), nullable=True),
    sa.Column('cost_accrual', sa.Float(), nullable=True),
    sa.Column('cost_committed_outstanding', sa.Float(), nullable=True),
    sa.Column('forecast_cost_to_complete', sa.Float(), nullable=True),
    sa.Column('metode_ctc', sa.String(length=30), nullable=True),
    sa.Column('forecast_final_cost', sa.Float(), nullable=True),
    sa.Column('forecast_final_value', sa.Float(), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cvr_period_id'], ['cvr_periods.id'], name='fk_cvr_lines_cvr_period_id'),
    sa.ForeignKeyConstraint(['rap_item_id'], ['rap_items.id'], name='fk_cvr_lines_rap_item_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accruals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rap_item_id', sa.Integer(), nullable=True),
    sa.Column('spk_id', sa.Integer(), nullable=True),
    sa.Column('periode', sa.String(length=10), nullable=True),
    sa.Column('nilai_estimasi', sa.Float(), nullable=True),
    sa.Column('dasar', sa.String(length=500), nullable=True),
    sa.Column('dibuat_oleh', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_accruals_project_id'),
    sa.ForeignKeyConstraint(['rap_item_id'], ['rap_items.id'], name='fk_accruals_rap_item_id'),
    sa.ForeignKeyConstraint(['spk_id'], ['spks.id'], name='fk_accruals_spk_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accruals')
    op.drop_table('cvr_lines')
    op.drop_table('cvr_commentaries')
    op.drop_table('cvr_periods')
    # ### end Alembic commands ###
