"""fase7: rap_kode identitas lintas versi + unique constraint

Revision ID: 8fe00e253a18
Revises: fc8cdc224528
Create Date: 2026-08-01 23:48:59.368568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe00e253a18'
down_revision: Union[str, Sequence[str], None] = 'fc8cdc224528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rap_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_rap_item_proyek_versi_kode', ['project_id', 'rap_version_id', 'kode_rap'])

    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rap_kode', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_spks_rap_kode'), ['rap_kode'], unique=False)

    with op.batch_alter_table('variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rap_kode', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_variations_rap_kode'), ['rap_kode'], unique=False)

    # Backfill rap_kode dari rap_items (Fase 7 — identitas lintas versi)
    op.execute("""
        UPDATE spks SET rap_kode = (
            SELECT kode_rap FROM rap_items WHERE rap_items.id = spks.rap_item_id
        ) WHERE rap_item_id IS NOT NULL;
    """)
    op.execute("""
        UPDATE variations SET rap_kode = (
            SELECT kode_rap FROM rap_items WHERE rap_items.id = variations.rap_item_id
        ) WHERE rap_item_id IS NOT NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variations_rap_kode'))
        batch_op.drop_column('rap_kode')

    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spks_rap_kode'))
        batch_op.drop_column('rap_kode')

    with op.batch_alter_table('rap_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rap_item_proyek_versi_kode', type_='unique')

    # ### end Alembic commands ###
