"""fase3: procurement, price_comparison, spk_status_log, variations

Revision ID: db21bb7ae641
Revises: 6c36c95efafb
Create Date: 2026-08-01 22:21:54.564038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db21bb7ae641'
down_revision: Union[str, Sequence[str], None] = '6c36c95efafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rap_item_id', sa.Integer(), nullable=True),
    sa.Column('nomor', sa.String(length=100), nullable=True),
    sa.Column('tanggal_ajukan', sa.Date(), nullable=True),
    sa.Column('nilai_ajukan', sa.Float(), nullable=True),
    sa.Column('vendor_terpilih_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_procurement_requests_project_id'),
    sa.ForeignKeyConstraint(['rap_item_id'], ['rap_items.id'], name='fk_procurement_requests_rap_item_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.String(length=50), nullable=True),
    sa.Column('rap_item_id', sa.Integer(), nullable=True),
    sa.Column('sumber', sa.String(length=30), nullable=True),
    sa.Column('tanggal_peristiwa', sa.Date(), nullable=True),
    sa.Column('tanggal_notice', sa.Date(), nullable=True),
    sa.Column('batas_notice', sa.Date(), nullable=True),
    sa.Column('uraian', sa.String(length=500), nullable=True),
    sa.Column('estimasi_biaya', sa.Float(), nullable=True),
    sa.Column('nilai_klaim_value', sa.Float(), nullable=True),
    sa.Column('dampak_waktu_hari', sa.Integer(), nullable=True),
    sa.Column('status_entitlement', sa.String(length=30), nullable=True),
    sa.Column('cco_ref', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_variations_project_id'),
    sa.ForeignKeyConstraint(['rap_item_id'], ['rap_items.id'], name='fk_variations_rap_item_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_request_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('lingkup_termasuk', sa.String(length=300), nullable=True),
    sa.Column('lingkup_tidak_termasuk', sa.String(length=300), nullable=True),
    sa.Column('terpilih', sa.Boolean(), nullable=True),
    sa.Column('alasan_tidak_dipilih', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], name='fk_price_comparisons_procurement_request_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spk_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spk_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('catatan', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['spk_id'], ['spks.id'], name='fk_spk_status_logs_spk_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_spks_variation_id', 'variations', ['variation_id'], ['id'])
        batch_op.create_foreign_key('fk_spks_procurement_request_id', 'procurement_requests', ['procurement_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spks_procurement_request_id', type_='foreignkey')
        batch_op.drop_constraint('fk_spks_variation_id', type_='foreignkey')

    op.drop_table('spk_status_logs')
    op.drop_table('price_comparisons')
    op.drop_table('variations')
    op.drop_table('procurement_requests')
    # ### end Alembic commands ###
