"""fase4: cvr_lines rap_item relationship (no schema change)

Revision ID: fc8cdc224528
Revises: 7fdb696d949e
Create Date: 2026-08-01 23:21:14.881985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8cdc224528'
down_revision: Union[str, Sequence[str], None] = '7fdb696d949e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
